### ISSUE TITLE
How to edit migrations in local development 

### ISSUE THREAD

**Issue by dzfranklin** [peterldowns/pgmigrate#9]
Suppose I'm working on a PR. I write a migration, apply it to my local dev database, then realize the migration should be different. What should I do next? 

With tern I would apply the down migration, edit the file, then apply the new up migration.

Based on your readme I can think of a few workarounds, but they'd be less convenient 

- edit the file, recalculate the checksum, and manually run sql commands to make my local dev database consistent with it
- drop and recreate my dev database 

Is there a better way to do this?

**Comment by peterldowns** [comment]
There are a couple of options, none of which are better or worse than any other. If you're used to working with `tern`, you can get a similar experience like this:

- Assuming
  - you're working on `123_newmigration.sql`
  - your DB url is `$DB_URL`
- Keep working on `123_newmigration.sql` but put your "down migration" in a file somewhere, for instance `down.sql`
- When you want to apply the down migration, run something like this:
  ```shell
  psql $DB_URL -f ./down.sql && pgmigrate op mark-unapplied 123_newmigration
  ```

Other options:

- Write some scripts for creating/resetting snapshots of your database
  - before starting work on `123_newmigration.sql`, run `snapshot create`
  - edit the sql, run `pgmigrate apply`
  - realize you want to change the migration
  - `snapshot restore` to get the dev db back into the state it was in when you ran `snapshot create` above
  - edit the sql, run `pgmigrate apply`
  - repeat as needed
- Instead of iterating on migrations with your dev db, iterate on migrations in throwaway/temporary databases, using something like [pgtestdb](https://github.com/peterldowns/pgtestdb) to quickly apply all of your migrations each time.

If there's enough interest, I would consider adding those snapshot tools to `pgmigrate` — but in my experience, everyone has their own way they prefer to do things.

**Comment by dzfranklin** [comment]
Thank you!

**Comment by peterldowns** [comment]
@dzfranklin out of curiosity, are you using pgmigrate yet, or are you considering switching to it? If you're evaluating it, I'd really appreciate any feedback when you eventually make a decision (either to try it or not) — it could help me a lot in terms of documentation and any missing features.

**Comment by dzfranklin** [comment]
I'm considering switching a personal project from tern to pgmigrate but I might not have time for a little while. I'll try and comment when I have thoughts about how it goes.

**Comment by peterldowns** [comment]
No obligation on your part, but any and all feedback or perspectives would be greatly appreciated!
